### ISSUE TITLE
cvDisplacementMapFilter out put not as per youtube video.

### ISSUE THREAD

**Issue by kinimatt** [karlphillip/GraphicsProgramming#6]
Hi @karlphillip I'm trying to achieve same result as shown in youtube video. I ran code from github as it is, result I get is different from video.  Foreground image is not white, its tinted blue (transparent?). What changes you made to get this result?﻿

I actually need to achieve it in C#. I have ported your code to C# using Opencvsharp. I get same result as your code. Foreground is tinted blue.

**Comment by karlphillip** [comment]
I just updated the code to fix a bug caused by OpenCV 3.x but it has nothing to do with the behaviour you described. If you'd like to give the new version a try:
[](https://github.com/karlphillip/GraphicsProgramming/blob/master/cvDisplacementMapFilter/main.cpp)

This is a GIF of the output:
https://gph.is/2CWDAJt

**Comment by karlphillip** [comment]
Glad to hear that! 

Come back when you are done and let us know what you did to make it smoother (if you can).
